os: linux
dist: xenial
language: shell

install: skip
script: sleep 10

jobs:
  include:
    - dist: bionic
      arch: arm64
    - dist: focal
      arch: arm64
    - dist: jammy
      arch: arm64
    - dist: bionic
      arch: arm64-graviton2
      group: edge
      virt: lxd
    - dist: focal
      arch: arm64-graviton2
      group: edge
      virt: lxd
    - dist: jammy
      arch: arm64-graviton2
      group: edge
      virt: lxd

deploy:
  provider: script
  on:
    all_branches: true
  script: echo "Hello"
